Fetch and display user data
esturide/esturide-frontend pull request #8
Opened 2024-03-07 16:58 UTC by Gesem-Martinez

- [x] Create a new hook useGetUserData to fetch user data
- [x] Add hook useEffect to fetch data on component render
- [x] Implement the new hook in the UserProfile page
- [x] Display the user name according to the data fetched
- [x] Fix layout styles to display the user data properly

2024-03-07 17:00 UTC, SealtielFreak approved these changes
Perfect, no problem

2024-03-07 17:07 UTC, AdalV51 requested changes

2024-03-07 17:07 UTC, AdalV51 commented on src/hooks/userGetUserData.tsx
> +  const localhost = '10.9.185.187';
Please change this to use a environment variable instead. 

This environment variable named have to contain the localhost + the port.

Investigate on how to create a `.env` file and set a env variable like this for your case:

```
LOCALHOST = 10.9.185.187:3000
```

2024-03-11 03:00 UTC, SealtielFreak approved these changes
It's ok

2024-03-11 16:27 UTC, AdalV51 approved these changes

2024-03-11 16:27 UTC, merged